### ISSUE TITLE
hangs when processing large number of files

### ISSUE THREAD

**Issue by Stardraw** [jonschlinkert/gulp-htmlmin#38] opened 2016-01-23 22:05 UTC
var htmlmin = require("gulp-htmlmin");

gulp.task("release-html", function () {
    return gulp.src("src/stardraw/company/pressreleases/*.html")
    .pipe(htmlmin({ lint: false, collapseWhitespace: true, }))
    .pipe(gulp.dest("wwwroot"));
});

This fails when we have 147 html files.
Only the first 30 odd files are converted - a different amount each time I run it - sometimes more, sometimes less.
I can individually htmlmin each html file successfully.
The gulp task just never ends.
If I comment out the pipe(htmlmin( line, all the files are copied over correctly.
It must therefore be an htmlmin problem.

My package.json file has:
    "gulp-htmlmin": "1.3.0",

**Comment by Stardraw** [comment] 2016-01-24 14:20
Well, I thought I had run htmlmin on each html file successfully, but it turns out I hadn't and had missed some files.
I found the invalid HTML and fixed it and now it runs through fine.
However, it still doesn't explain why it should just hang and not produce ANY errors when running through multiple files.

**Comment by marjan-georgiev** [comment] 2016-02-10 19:09
I'm seeing the same issue. The task just hands without throwing any errors.

**Comment by jonschlinkert** [comment] 2016-02-10 21:54
duplicate of https://github.com/jonschlinkert/gulp-htmlmin/issues/35

**Closed by jonschlinkert** 2016-02-10 21:54 UTC
