### ISSUE TITLE
TypeError in gulp-uglify in conjunction with gulp-htmlmin

### ISSUE THREAD

**Issue by jordansexton** [jonschlinkert/gulp-htmlmin#22] opened 2015-04-16 09:34 UTC
Cross posted from [gulp-uglify#101](https://github.com/terinjokes/gulp-uglify/issues/101) since I think it might be a bug with `gulp-htmlmin`.
Please see [gulp-uglify-htmlmin-bug](https://github.com/jordansexton/gulp-uglify-htmlmin-bug) to reproduce.

It might be due to sharing the uglify options object and perhaps it's being mutated by this library.

**Comment by shinnn** [comment] 2015-04-16 09:50
I confirmed the problem. Thanks for reporting.

It should be fixed in [the upstream project](https://github.com/kangax/html-minifier). These line would be the cause: https://github.com/kangax/html-minifier/blob/b1529189508b50ad4a837f261caf863054a7543f/src/htmlminifier.js#L491-L494

Could you report it to [kangax/html-minifier's issue tracker](https://github.com/kangax/html-minifier/issues)?

And, you can close https://github.com/terinjokes/gulp-uglify/issues/101 since it's not related to this issue.

**Comment by thinkive** [comment] 2015-11-12 01:37
我发现一个不知道算不算是bug，如果我压缩的html文件里面没有html标准头(只有div)信息，则压缩不会成功(很多一起，会成功1-2个)，如果压缩标准html页面没问题

**Comment by shinnn** [comment] 2015-11-12 02:46
http://www.catb.org/esr/faqs/smart-questions.html#writewell

**Comment by thinkive** [comment] 2015-11-12 09:30
我需要先翻译为英文吗？

**Comment by shinnn** [comment] 2015-11-12 09:46
Yep.

**Comment by thinkive** [comment] 2015-11-12 11:53
I found a not known as bug, if I do not compress the HTML file HTML standard header (only DIV), then the compression will not be successful (many together, the success of 1-2), if the compression standard HTML page no problem

**Comment by shinnn** [comment] 2015-11-12 12:28
That's not related to #22 and seems to be an [html-minifier](https://github.com/kangax/html-minifier) issue. Report it to the proper issue tracker.

**Comment by jonschlinkert** [comment] 2016-09-24 11:37
anyone know if this was _actually_ fixed in html-minifier? I quickly looked over the code in html-minifier and didn't see options being shallow cloned anywhere. I just want to make sure they're not mutating the options object still, so we can close this

**Comment by jonschlinkert** [comment] 2018-09-08 11:16
fixed

**Closed by jonschlinkert** 2018-09-08 11:16 UTC
