### ISSUE TITLE
keepClosingSlash not working

### ISSUE THREAD

**Issue by steviemo** [jonschlinkert/gulp-htmlmin#92] opened 2018-02-23 10:47 UTC
I have some html with a bunch of closing <img .. />, 
tags and html-minifier is still stripping out the closing tags after executing the following options:

.pipe($.htmlmin, { keepClosingSlash: true});

I have confirmed it's not an issue with html-minifier : https://github.com/kangax/html-minifier/issues/886

Cheers,
Stephen

**Comment by doowb** [comment] 2018-02-23 10:55
If that's the code you're using, then you're passing the arguments to the wrong function. 

```js 
.pipe($.htmlmin({ keepClosingSlash: true}));
```

**Comment by steviemo** [comment] 2018-02-23 11:28
FYI I have sent down additional properties to htmlmin such as collapseWhitespace: true and these have taken affect OK - just seems that keepClosingSlash doesn't get passed down to html-minifier.

**Comment by doowb** [comment] 2018-02-23 17:48
@steviemo I created [this repo](https://github.com/doowb/gulp-htmlmin-keep-closing-slash) to attempt to reproduce your issue, but it's working as expected.

I'm going to close this issue since there's probably something else wrong (maybe `inlineCss` is removing the slash... just a guess).

**Closed by doowb** 2018-02-23 17:48 UTC

**Comment by xmsz** [comment] 2019-06-12 06:33
I found my problem was relative to `<input></input>`

**Comment by diyorbek** [comment] 2019-11-25 12:36
> @steviemo I created [this repo](https://github.com/doowb/gulp-htmlmin-keep-closing-slash) to attempt to reproduce your issue, but it's working as expected.
> 
> I'm going to close this issue since there's probably something else wrong (maybe `inlineCss` is removing the slash... just a guess).

In my case, it was indeed `inlineCss` plugin issue. I added `xmlMode: true` to its configuration and everything worked.
